### ISSUE TITLE
Back up hypercore metadata

### ISSUE THREAD

**Issue by hiimalexjgarcia** [USHIN-Inc/ushin-ui-components#127]
Wasn't quite sure whether this should be an app feature or db issue, but anyway... There should be a way to back up the user's messages, points, and author metadata. In the case of persistence with hyercore, there should be a way to back up the hypercore itself -- in the case we need to trasnsfer data to another device. How does this sound?

**Comment by RangerMauve** [comment]
Good idea. I've been investigating backups and restores recently in my [hyperdrive-publisher](https://github.com/RangerMauve/hyperdrive-publisher) module.

For backups, I've made a bunch of progress in [dat-store](https://github.com/datproject/dat-store) with Hyperdrives, and I think it would be easy enough to adapt to Hypercores in general.

I've also been talking with some other folks building on the tech about standardizing around that. Could be worth it to have a small call with people interested in collaborating on this.

For backups, since we're using dat-sdk and the underlying "corestore" module, we'd only need to back up the "master key" which is used to derive all the other private keys for hypercores generated in the app.

Restoring could be a matter of populating the master key of a corestore, and loading all your history from the p2p network on boot (which is more or less automatic, but I'm ironing out some kinks in hyperdrive-publisher)
